# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
variables:
  tag: $(Build.BuildId)

stages:
- stage: Build
  displayName: Build And Push to Docker Container
  jobs:
    - job: Build
      pool:
       name: agent1
 # Task-1: Build Docker Image and push to Azure Container Registry ACR
      steps:
        - task: Docker@2
          inputs:
            containerRegistry: 'manual-aksdevopsacr-svc'
            repository: 'custom2aksnginxapp1'
            command: 'buildAndPush'
            Dockerfile: '**/Dockerfile'
            tags: |
              $(tag)
              $(Build.SourceBrar)
            
# Publish Artifacts pipeline code in addition to Build and Push             
        - bash: echo Source folder before copying ; ls -lrt $(System.DefaultWorkingDirectory)
        - bash: echo Target folder before copying ; ls -lrt $(Build.ArtifactStagingDirectory)
        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(System.DefaultWorkingDirectory)/kube-manifests'
            Contents: '**'
            TargetFolder: '$(Build.ArtifactStagingDirectory)'
            OverWrite: true
# List files from Build Artifact Staging Directory - After Copy
        - bash: echo Build Artifact Staging Directory - After Copy; ls -lrt $(Build.ArtifactStagingDirectory)
        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: '$(Build.ArtifactStagingDirectory)'
            ArtifactName: 'kube-manifests'
            publishLocation: 'Container'

        
         
